site_name: tanzu-developer-portal
site_description: Tanzu Developer Portal
site_author: user:ben.wilcock
nav:
  - "Welcome To VMware® Tanzu Developer Portal™": index.md
  - "Why Choose VMware® Tanzu Developer Portal™?": why-choose-tdp.md
  - "Getting Started With VMware® Tanzu Developer Portal™": get-started.md 
  - "Feature Highlights Of VMware® Tanzu Developer Portal™": features.md
  - "What's Included With VMware® Tanzu Developer Portal™": whats-in-the-box.md
  - "Getting Help With VMware® Tanzu Developer Portal™": help.md
  - "FAQs For VMware® Tanzu Developer Portal™": faqs.md
  # - "MKDocs Extensions": mkdocs-extensions.md
  # - 'Tanzu Labs - Modernization Recipes':
  #   - 'REST API Design': recipes/rest-api-design.md
  #   - 'REST API Versioning' : recipes/rest-api-versioning.md
  #   - 'Get Started With Git': recipes/get-started-with-git.md
  
plugins:
  - techdocs-core
metadata:
  namespace: default
kind: system