apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-developer-portal
  labels:
    apps.tanzu.vmware.com/workload-type: techdocs
    app.kubernetes.io/part-of: tanzu-developer-portal
  namespace: polyglot-demo
spec:
  params:
    - name: techdocs_type
      value: "system"
  source:
    git:
      url: https://github.com/benwilcock/systems-techdocs
      ref:
        branch: main
    subPath: tanzu-developer-portal-system